---
title: "Computational Intelligence I Assignment"
author: "Gaelan Gu"
date: "20/04/2017"
output: word_document
---

# Neural Network Ensemble for Diabetes Dataset

```{r}
# Data import
diabetes = read.csv('./datasets/Diabetes.csv', header = F)
colnames(diabetes) = c('no.of.times.preg', 'plasma.glucose.conc', 'diastolic.pressure',
                       'triceps.skin.fold.thick', 'serum.insulin', 'bmi', 'diab.pedigree.func',
                       'age', 'positive.test')

# Factorizing class variable
diabetes$positive.test = as.factor(as.character(diabetes$positive.test))

summary(diabetes)
```

```{r}
# Train-test split
library(caTools)
set.seed(111)
diabetes$split = sample.split(diabetes$positive.test, SplitRatio = 0.7)

diabetes_train = subset(diabetes, split == T)
diabetes_test = subset(diabetes, split == F)

# Excluding split columns
diabetes_train = diabetes_train[-10]
diabetes_test = diabetes_test[-10]

# Writing CSV for train and test
write.table(diabetes_train, sep = ',', file = './datasets/Diabetes_train.csv', row.names = F)
write.table(diabetes_test, sep = ',', file = './datasets/Diabetes_test.csv', row.names = F)
```

```{r}
# Loading neural net packages
# install.packages(c('nnet', 'neuralnet', 'pnn', 'RSNNS', 'NeuralNetTools'))
library(nnet)
library(neuralnet)
library(grnn)
library(RSNNS)
library(NeuralNetTools)
```

## Single-Layer Neural Network

```{r}
# Building the neural net model
diabetes_nnet = nnet(positive.test ~ ., data = diabetes_train,
                     size = 8, maxit = 10000, decay = 0.0001)

summary(diabetes_nnet)
```


```{r}
# Prediction and confusion matrix
pred = predict(diabetes_nnet, newdata = diabetes_test, type = 'class')
cm = table(true = diabetes_test$positive.test, predicted = pred)
library(caret)
cm1 = confusionMatrix(cm)
cm1
```

Accuracy of **72.2%** achieved.


## General Regression Neural Network

```{r}
# Unfactorizing class variable
diabetes_train$positive.test = as.numeric(as.character(diabetes_train$positive.test))
diabetes_test$positive.test = as.numeric(as.character(diabetes_test$positive.test))

# Building the GRNN
diabetes_gnet = learn(set = diabetes_train, variable.column = length(diabetes_train))
diabetes_gnet = smooth(diabetes_gnet, sigma = 2.8)

diabetes_test$predict = -1
diabetes_testsub = diabetes_test[, 1:8]

vec = as.matrix(diabetes_testsub[7, ])
res = guess(diabetes_gnet, vec)

for(i in 1:nrow(diabetes_testsub)) {
  vec = as.matrix(diabetes_testsub[i, ])
  res = guess(diabetes_gnet, vec)
  
  if(anyNA(res)) {
    cat("Entry ",i," Generated NaN result!\n")
  } else{
    diabetes_test$predict[i] = res
  }
}

# Rounding predictions
diabetes_test$predictclass = round(diabetes_test$predict)
```

## Accuracy of Test Set
```{r}
result_size = nrow(diabetes_test)
result_correct = nrow(diabetes_test[diabetes_test$predictclass == diabetes_test$positive.test, ])
grnn_accuracy = result_correct / result_size
grnn_accuracy
```

Accuracy of **67.4%** achieved on test set.



# Neural Network Emsemble for Wine Quality Dataset

```{r}
# Data import
# wine = read.csv('./datasets/winequality-white.csv')
# 
# summary(wine)
```

```{r}
# Train-test split
# set.seed(111)
# wine$split = sample.split(wine$quality, SplitRatio = 0.7)
# 
# wine_train = subset(wine, split == T)
# wine_test = subset(wine, split == F)
# 
# # Excluding split columns
# wine_train = wine_train[-13]
# wine_test = wine_test[-13]
# 
# # Writing CSV for train and test
# write.table(wine_train, sep = ',', file = './datasets/winequality_train.csv', row.names = F)
# write.table(wine_test, sep = ',', file = './datasets/winequality_test.csv', row.names = F)
```